=== Sen-Riya/WSD-Lab5/courses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:cs="http://www.example.com/course"
           targetNamespace="http://www.example.com/course"
           elementFormDefault="qualified">

    <xs:element name="courses">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="course" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="instructor" type="xs:string"/>
                            <xs:element name="duration" type="xs:decimal"/>
                            <xs:element name="availability" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Sen-Riya/WSD-Lab5/courses.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="courses.xsl" type="text/xsl" ?>
<courses
    xmlns="http://www.example.com/course"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.example.com/course courses.xsd"
>

    <course>
        <title>Introduction to Programming</title>
        <instructor>Dr.Maruthi</instructor>
        <duration>10</duration> 
        <availability>Available</availability>
    </course>
    <course>
        <title>Advanced Mathematics</title>
        <instructor>Dr.Abeda</instructor>
        <duration>15</duration>
        <availability>Not Available</availability>
    </course>
    <course>
        <title>Data Science Basics</title>
        <instructor>Dr.Rekha</instructor>
        <duration>12</duration>
        <availability>Available</availability>
    </course>
</courses>
